title: Programming Handbook
description: An open-source platform for sharing and preserving programming knowledge. Discover code snippets, best practices, and resources, all continuously updated by a thriving community of developers. Join us to collaborate and enhance your coding skills in one comprehensive space.
theme: just-the-docs

url: https://just-the-docs.github.io

github_base_url: "https://github.com/VerzatileDevOrg/Programming_HandBook"

aux_links:
  Contribute to the Github Repository: https://github.com/VerzatileDevOrg/Programming_HandBook

plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d/%m/%Y'

# Color Theme
color_scheme: light